name: Terraform Deploy

on:
  workflow_dispatch: # 수동 실행

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="gh_username=${{ secrets.GH_USERNAME }}" \
            -var="gh_token=${{ secrets.GH_TOKEN }}" \
            -var="mongodb_username=${{ secrets.MONGODB_USERNAME }}" \
            -var="mongodb_password=${{ secrets.MONGODB_PASSWORD }}" \
            -var="mongodb_host=${{ secrets.MONGODB_HOST }}" \
            -var="mongodb_database=${{ secrets.MONGODB_DATABASE }}" \
            -var="docdb_uri=${{ secrets.DOCDB_URI }}"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="gh_username=${{ secrets.GH_USERNAME }}" \
            -var="gh_token=${{ secrets.GH_TOKEN }}" \
            -var="mongodb_username=${{ secrets.MONGODB_USERNAME }}" \
            -var="mongodb_password=${{ secrets.MONGODB_PASSWORD }}" \
            -var="mongodb_host=${{ secrets.MONGODB_HOST }}" \
            -var="mongodb_database=${{ secrets.MONGODB_DATABASE }}" \
            -var="docdb_uri=${{ secrets.DOCDB_URI }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
